server:
  port: ${SERVER_PORT:8080}

spring:
  redis:
    host: ${REDIS_HOST:10.52.2.205}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:90-=op[]}
    database: ${REDIS_DATABASE:10}
  rabbitmq:
    addresses: ${RABBITMQ_HOST:localhost:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    exchange:
      name: test_exchange
      durable: true
      autoDelete: false
    queue:
      name: test_queue
      durable: true
      exclusive: false
      autoDelete: false
      routekey: test_routekey
db:
  mysql_1:
    driverClass: com.mysql.jdbc.Driver
    maxActive: 20
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    initialSize: 0
    minIdle: 0
    maxWait: 60000
    validationQuery: "SELECT 1"
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true

  mysql_2:
    driverClass: com.mysql.jdbc.Driver
    maxActive: 20
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    initialSize : 0
    minIdle: 0
    maxWait: 60000
    validationQuery: "SELECT 1"
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true

#允许跨域的域名及端口
domain:
   - http://localhost:9527
   - http://127.0.0.1:9527


